# Site settings
title: "Aldebaran"
description: "GaiusCoffee's Tree of Savior Blog" 
url: 'http://gaius.coffee/'
baseurl: 'blog/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'gaiuscoffee'

author:
  name: 'Erik Gaius Capistrano'
  email: gaius.coffee@gmail.com
  twitter_username: gaiuscoffee
  facebook_username: gaiuscoffee
  github_username:  gaiuscoffee
#  linkedin_username:  gaiuscoffee

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jemoji']
exclude: ['Gemfile', 'Gemfile.lock']
